src/UserBundle/Entity/User.php
<?php

namespace Rabble\UserBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\PersistentCollection;
use Gedmo\Timestampable\Traits\Timestampable;
use Rabble\UserBundle\UserActivity\AuditActivity\AuditSubjectInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Entity\File as EmbeddedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @Vich\Uploadable
 * @UniqueEntity("username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface, \Serializable, EquatableInterface, AuditSubjectInterface
{
    use Timestampable;

    protected int $id;

    protected string $username;
    /**
     * @Assert\NotBlank()
     */
    protected ?string $password;

    protected bool $superAdmin = false;

    protected string $firstName;

    protected string $lastName;

    protected ?string $bio;

    /** @var Collection<Role> */
    protected Collection $roles;

    /** @var PersistentCollection<UserSetting> */
    protected Collection $settings;

    protected EmbeddedFile $image;

    protected ?string $avatar;

    /**
     * @Vich\UploadableField(mapping="user", fileNameProperty="image.name", size="image.size", mimeType="image.mimeType", originalName="image.originalName", dimensions="image.dimensions")
     */
    protected ?File $imageFile = null;

    public function __construct()
    {
        $this->settings = new ArrayCollection();
        $this->roles = new ArrayCollection();
        $this->image = new EmbeddedFile();
    }

    /**
     * @return string[]
     */
    public function getRoles(): array
    {
        $roles = ['ROLE_RABBLE_ADMIN'];
        $children = [];
        foreach ($this->roles as $role) {
            $roles[] = $role->getRoleName();
            $children[] = $role->getId();
        }
        foreach ($this->roles as $role) {
            foreach ($role->getHierarchy($children) as $parentRole) {
                $roles[] = $parentRole->getRoleName();
            }
        }
        if ($this->isSuperAdmin()) {
            $roles[] = 'ROLE_RABBLE_SUPER_ADMIN';
        }

        return array_unique($roles);
    }

    /**
     * @return Collection<Role>
     */
    public function getUserRoles()
    {
        return $this->roles;
    }

    public function setUserRoles($roles): void
    {
        $this->roles = $roles;
    }

    /**
     * @return ArrayCollection<UserSetting>
     */
    public function getSettings(): Collection
    {
        return $this->settings;
    }

    public function setSettings(ArrayCollection $settings): void
    {
        $this->settings = $settings;
    }

    public function getSetting($key, ?string $default = null): ?string
    {
        if (!isset($this->settings) || !$this->settings instanceof PersistentCollection) {
            return $default;
        }
        $setting = $this->settings->matching(Criteria::create()->where(Criteria::expr()->eq('key', $key)));
        if (0 === $setting->count()) {
            return $default;
        }
        $setting = $setting->first();

        return $setting->getValue();
    }

    public function addSetting($key, string $value): void
    {
        if (!$this->settings instanceof PersistentCollection) {
            return;
        }
        $setting = $this->settings->matching(Criteria::create()->where(Criteria::expr()->eq('key', $key)))->first();
        if (!$setting instanceof UserSetting) {
            $setting = new UserSetting();
            $setting->setUser($this);
            $this->settings->add($setting);
        }
        $setting->setKey($key);
        $setting->setValue($value);
    }

    /**
     * @return Role[]
     */
    public function getRoleHierarchy(): array
    {
        $roles = [];
        $children = [];
        foreach ($this->roles as $role) {
            $roles[] = $role;
            $children[] = $role->getId();
        }
        foreach ($roles as $role) {
            foreach ($role->getHierarchy($children) as $parentRole) {
                $roles[] = $parentRole;
                $children[] = $parentRole->getId();
            }
        }

        return array_unique($roles, SORT_REGULAR);
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): void
    {
        if (null !== $password) {
            $this->password = $password;
        }
    }

    public function isSuperAdmin(): bool
    {
        return $this->superAdmin;
    }

    public function setSuperAdmin(bool $superAdmin): void
    {
        $this->superAdmin = $superAdmin;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): void
    {
        $this->firstName = $firstName;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): void
    {
        $this->lastName = $lastName;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): void
    {
        $this->bio = $bio;
    }

    public function setImageFile(?File $imageFile = null)
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTime();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImage(EmbeddedFile $image): void
    {
        $this->image = $image;
    }

    public function getImage(): ?EmbeddedFile
    {
        return $this->image;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): void
    {
        $this->avatar = $avatar;
    }

    /**
     * @return null|string
     */
    public function getSalt()
    {
        return 'RabbleSalt';
    }

    /**
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    public function getUserIdentifier(): string
    {
        return $this->getUsername();
    }

    public function eraseCredentials()
    {
    }

    public function serialize()
    {
        return serialize([
            $this->id,
            $this->username,
            $this->password,
        ]);
    }

    public function unserialize($serialized)
    {
        [
            $this->id,
            $this->username,
            $this->password
        ] = unserialize($serialized, [static::class]);
    }

    /**
     * @return bool
     */
    public function isEqualTo(UserInterface $user): bool
    {
        return $this->username === $user->getUserIdentifier();
    }

    public function getAuditSubject(): string
    {
        return sprintf('%s %s', $this->firstName, $this->lastName);
    }

    public function getAuditSubjectType(): string
    {
        return 'user';
    }
}

src/UserBundle/Controller/UserController.php
<?php

namespace Rabble\UserBundle\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Rabble\AdminBundle\Ui\Panel\ContentPanel;
use Rabble\AdminBundle\Ui\Panel\Tab;
use Rabble\AdminBundle\Ui\Panel\TabbedPanel;
use Rabble\UserBundle\Entity\User;
use Rabble\UserBundle\Event\UserCreateEvent;
use Rabble\UserBundle\Event\UserEditEvent;
use Rabble\UserBundle\Event\UserFormEvent;
use Rabble\UserBundle\Event\UserViewEvent;
use Rabble\UserBundle\Form\UserType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Contracts\Translation\TranslatorInterface;

class UserController extends AbstractController
{
    private EventDispatcherInterface $eventDispatcher;

    private TranslatorInterface $translator;

    public function __construct(EventDispatcherInterface $eventDispatcher, TranslatorInterface $translator)
    {
        $this->eventDispatcher = $eventDispatcher;
        $this->translator = $translator;
    }

    /**
     * @Security("is_granted('user.view')")
     */
    public function indexAction(): Response
    {
        return $this->render('@RabbleUser/User/index.html.twig');
    }

    /**
     * @ParamConverter("user", converter="implemented_entity", options={"entity" = "User"})
     * @Security("is_granted('user.view')")
     */
    public function viewAction(Request $request, User $user): Response
    {
        /** @var UserViewEvent $event */
        $event = $this->eventDispatcher->dispatch(new UserViewEvent($user, $request));

        return $this->render('@RabbleUser/User/view.html.twig', [
            'user' => $user,
            'actionRow' => $event->getActionRow(),
            'leftPanes' => $event->getLeftPanes(),
            'rightPanes' => $event->getRightPanes(),
        ]);
    }

    /**
     * @Security("is_granted('user.create')")
     */
    public function createAction(Request $request, EntityManagerInterface $entityManager): Response
    {
        $userClass = $entityManager->getRepository('User')->getClassName();
        /** @var User $user */
        $user = new $userClass();
        $form = $this->createForm(UserType::class, $user)->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->addFlash('success', 'The user has been saved.');
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('rabble_admin_user_index');
        }
        $formView = $form->createView();
        /** @var UserFormEvent $formEvent */
        $formEvent = $this->eventDispatcher->dispatch(new UserFormEvent(
            $user,
            $form,
            $request,
            new TabbedPanel([
                'tabs' => [new Tab([
                    'label' => $this->translator->trans('menu.user.create', [], 'RabbleUserBundle'),
                    'content' => $this->renderView('@RabbleUser/User/form.html.twig', [
                        'form' => $formView,
                        'heading' => $this->translator->trans('menu.user.create', [], 'RabbleUserBundle'),
                    ]),
                ])],
            ])
        ));
        /** @var UserCreateEvent $event */
        $event = $this->eventDispatcher->dispatch(new UserCreateEvent($user, $form, $request, [
            'default' => [
                new ContentPanel([
                    'no_container' => true,
                    'content' => $this->renderView('@RabbleUser/User/create/form.html.twig', [
                        'form' => $formView,
                        'container' => $formEvent->getPane(),
                    ]),
                ]),
            ],
        ]));

        return $this->render('@RabbleUser/User/create.html.twig', [
            'panes' => $event->getPanesFlattened(),
        ]);
    }

    /**
     * @ParamConverter("user", converter="implemented_entity", options={"entity" = "User"})
     * @Security("(is_granted(request.attributes.get('user')) || is_granted('role.overrule')) && is_granted('user.edit')")
     */
    public function editAction(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user)->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->addFlash('success', 'The user has been saved.');
            $entityManager->flush();
            $entityManager->refresh($user);
            $form = $this->createForm(UserType::class, $user);
        }
        $formView = $form->createView();
        /** @var UserFormEvent $formEvent */
        $formEvent = $this->eventDispatcher->dispatch(new UserFormEvent(
            $user,
            $form,
            $request,
            new TabbedPanel([
                'tabs' => [new Tab([
                    'label' => $this->translator->trans('menu.user.edit', [], 'RabbleUserBundle'),
                    'content' => $this->renderView('@RabbleUser/User/form.html.twig', [
                        'form' => $formView,
                        'user' => $user,
                        'heading' => $this->translator->trans('menu.user.edit', [], 'RabbleUserBundle'),
                    ]),
                ])],
            ])
        ));
        /** @var UserCreateEvent $event */
        $event = $this->eventDispatcher->dispatch(new UserEditEvent($user, $form, $request, [
            'default' => [
                new ContentPanel([
                    'no_container' => true,
                    'content' => $this->renderView('@RabbleUser/User/edit/form.html.twig', [
                        'form' => $formView,
                        'user' => $user,
                        'container' => $formEvent->getPane(),
                    ]),
                ]),
            ],
        ]));

        return $this->render('@RabbleUser/User/edit.html.twig', [
            'panes' => $event->getPanesFlattened(),
        ]);
    }

    /**
     * @ParamConverter("user", converter="implemented_entity", options={"entity" = "User"})
     * @Security("(is_granted(request.attributes.get('user')) || is_granted('role.overrule')) && is_granted('user.delete')")
     */
    public function deleteAction(User $user, EntityManagerInterface $entityManager): Response
    {
        if ($user === $this->getUser()) {
            return $this->redirectToRoute('rabble_admin_user_index');
        }
        $entityManager->remove($user);
        $entityManager->flush();

        return $this->redirectToRoute('rabble_admin_user_index');
    }
}

src/UserBundle/Resources/views/User/create.html.twig
{% extends '@RabbleAdmin/Layout/base.html.twig' %}
{% trans_default_domain 'RabbleUserBundle' %}
{% block title %}{{ 'menu.user.create'|trans }}{% endblock %}
{% block page_content %}
    {% for pane in panes %}
        {{ rabble_admin_ui(pane) }}
    {% endfor %}
{% endblock %}

src/UserBundle/Resources/views/User/edit.html.twig
{% extends '@RabbleAdmin/Layout/base.html.twig' %}
{% trans_default_domain 'RabbleUserBundle' %}
{% block title %}{{ 'menu.user.edit'|trans }}{% endblock %}
{% block page_content %}
    {% for pane in panes %}
        {{ rabble_admin_ui(pane) }}
    {% endfor %}
{% endblock %}

src/UserBundle/Resources/views/User/form.html.twig
{% trans_default_domain 'RabbleUserBundle' %}
{% if heading|default %}
    <h4 class="c-grey-900 mB-20">{{ heading }}</h4>
{% endif %}
<div class="row">
    <div class="col-sm-8 col-lg-9 col-xl-10">
        {{ form_row(form.username) }}
    </div>
    <div class="col-sm-4 col-lg-3 col-xl-2">
        {{ form_row(form.userRoles) }}
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        {{ form_row(form.password.first) }}
    </div>
    <div class="col-sm-6">
        {{ form_row(form.password.second) }}
    </div>
</div>
<h5 class="c-grey-900 mB-10">{{ 'user.edit_personal'|trans }}</h5>
<hr/>
<div class="row">
    <div class="col-sm-6">
        {{ form_row(form.firstName) }}
    </div>
    <div class="col-sm-6">
        {{ form_row(form.lastName) }}
    </div>
</div>
{% if user is defined and user.id is not null %}
    <div class="row">
        <div class="col-sm-8 col-md-10">
            {{ form_row(form.imageFile) }}
        </div>
        <div class="col-sm-4 col-md-2 d-sm-flex d-none stron">
            <div class="row">
                <div class="col-12 text-center font-weight-bold">
                    <label>{{ 'form.current_image'|trans }}</label>
                </div>
                {% set avatar = asset('admin/build/assets/static/images/default-avatar.png') %}
                {% if user.avatar is defined and user.avatar is not null %}
                    {% set avatar = user.avatar %}
                {% endif %}
                <div class="col-12 text-center">
                    <img class="img-fluid bdrs-50p" src="{{ avatar }}" alt="avatar"/>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{{ form_widget(form) }}

src/UserBundle/Resources/views/User/index.html.twig
{% extends '@RabbleAdmin/Layout/base.html.twig' %}
{% trans_default_domain 'RabbleUserBundle' %}
{% block page_content %}
    <div class="row">
        <div class="col-12 mB-20">
            {% include '@RabbleAdmin/flash_messages.html.twig' with {mb: 3} only %}
            {% if is_granted('user.create') %}
                <a href="{{ path('rabble_admin_user_create') }}" class="btn btn-info"><i class="fa fa-plus-circle"></i> {{ 'user.create'|trans }}</a>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">
                <h4 class="c-grey-900 mB-20">{% block title %}{{ 'menu.user'|trans }}{% endblock %}</h4>
                {{ datatable('user') }}
            </div>
        </div>
    </div>
{% endblock %}

src/UserBundle/Resources/views/User/view.html.twig
{% extends '@RabbleAdmin/Layout/base.html.twig' %}
{% trans_default_domain 'RabbleUserBundle' %}
{% block title %}{{ 'menu.user'|trans }} - {{ user.firstName }} {{ user.lastName }}{% endblock %}
{% block page_content %}
    <div class="row">
        <div class="col-md-4">
            {% for panes in leftPanes %}
                {% for leftPane in panes %}
                    {{ rabble_admin_ui(leftPane) }}
                {% endfor %}
            {% endfor %}
        </div>
        <div class="col-md-8">
            {% for panes in rightPanes %}
                {% for rightPane in panes %}
                    {{ rabble_admin_ui(rightPane) }}
                {% endfor %}
            {% endfor %}
        </div>
    </div>
{% endblock %}